// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for flexible configuration
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://zcnhuvydqpotvgvwfcxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjbmh1dnlkcXBvdHZndndmY3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjA3MjMsImV4cCI6MjA3MjgzNjcyM30.i8Ne1z1YwJgtw3HVtyJuViAEmQmow5DJFlYAtrYerH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});